Repository JuliaRegistries/CompatHelper.jl, pull requests merged in 2019-11, with the labels that each got.

#39 Implement the `precommit_hook` feature
  src/main.jl
  src/new_versions.jl
Labels: enhancement

#48 Actions Setup hint
  README.md
Labels: documentation

#61 Mention how to update `Manifest.toml` files
  README.md
Labels: documentation

#106 Document the `master_branch` keyword argument
  README.md
Labels: documentation

#105 Add "Custom Registries" section to README
  README.md
Labels: documentation

#104 Automatically update all Manifest files
  .gitignore
  README.md
  src/CompatHelper.jl
  src/main.jl
  src/update_manifests.jl
  src/utils.jl
  test/integration-tests.jl
  test/templates/master_5/.gitignore
  test/templates/master_5/Manifest.toml
  test/templates/master_5/Project.toml
  test/templates/master_5/src/compathelper_integration_test_repo.jl
  test/templates/master_5/test/runtests.jl
Labels: breaking change

#109 Set delete_old_manifest=false by default
  src/update_manifests.jl
Labels: breaking change

#119 Bump version from "0.2.2-DEV" to "0.3.0-DEV"
  Project.toml
Labels: breaking change

#158 GitHub Actions is no longer in beta
  README.md
Labels: documentation
