Repository JuliaRegistries/CompatHelper.jl, pull requests merged in 2020-05, with the labels that each got.

#197 Add support for SSH deploy keys
  Project.toml
  README.md
  bors.toml
  src/new_versions.jl
  test/Project.toml
  test/integration-tests.jl
  test/runtests.jl
Labels: enhancement

#203 Refactor code, fix some bugs, and update the documentation
  .github/workflows/VersionVigilante_bors.yml
  .github/workflows/VersionVigilante_pull_request.yml
  Project.toml
  README.md
  src/main.jl
  src/new_versions.jl
Labels: bugfix, documentation, enhancement

#205 Support both the raw private key and the Base64-encoded private key
  Project.toml
  README.md
  src/CompatHelper.jl
  src/main.jl
  src/new_versions.jl
  src/ssh_keys.jl
  src/types.jl
  test/integration-tests.jl
  test/unit-tests.jl
Labels: enhancement

#204 Update README.md with 3-Troubleshooting
  Project.toml
  README.md
Labels: documentation

#207 A few small improvements to the README
  Project.toml
  README.md
Labels: documentation
