Repository JuliaRegistries/CompatHelper.jl, pull requests merged in 2021-08, with the labels that each got.

#365 Bug-fix for bump_package_version! when Project version is undefined
  src/utilities/new_versions.jl
  test/utilities/new_versions.jl
Labels: v3-dev

#374 Compare GH repos on fields rather than ==
  Project.toml
  src/pull_requests.jl
  test/patches.jl
  test/pull_requests.jl
Labels: bug fix

#382 Additional checks for SSH Private Key
  Project.toml
  src/pull_requests.jl
  src/utilities/utilities.jl
Labels: bug fix

#393 Test suite: remove the "`version =` line in the workflow file" test, in anticipation of recommending that users use the compathelper-action composite action
  test/runtests.jl
Labels: test suite
