Repository JuliaRegistries/CompatHelper.jl, pull requests merged in 2021-06, with the labels that each got.

#327 Test suite: small tweak to a Regex test
  test/runtests.jl
Labels: test suite, v3-dev

#330 Fix a bug where CompatHelper opens PRs to bump to e.g. "2.0" or "2.1", instead of just "2"
  Project.toml
  src/version_numbers.jl
  test/unit-tests.jl
Labels: bug fix

#323 Get latest version from registries
  Project.toml
  src/CompatHelper.jl
  src/dependencies.jl
  src/utilities/git.jl
  src/utilities/types.jl
  src/utilities/utilities.jl
  test/dependencies.jl
  test/deps/registry_1/PackageA/Versions.toml
  test/deps/registry_1/PackageB/Versions.toml
  test/deps/registry_1/Registry.toml
  test/deps/registry_2/PackageC/Versions.toml
  test/deps/registry_2/Registry.toml
  test/patches.jl
  test/pull_requests.jl
  test/runtests.jl
  test/utilities/git.jl
  test/utilities/types.jl
Labels: v3-dev

#335 [v3-dev] Some style tweaks: replace `using Foo` with `using Foo: Foo`, etc.
  bors.toml
  src/CompatHelper.jl
  test/patches.jl
  test/runtests.jl
  test/utilities/ssh.jl
Labels: v3-dev

#336 [v3-dev] Bors: require the Codecov checks
  .github/workflows/ci_integration.yml
  bors.toml
Labels: ci, v3-dev

#337 Use the `CODECOV_TOKEN` when submitting to Codecov
  .github/workflows/ci_integration.yml
Labels: ci
