Repository JuliaRegistries/CompatHelper.jl, pull requests merged in 2021-05, with the labels that each got.

#295 [docs] Remove statement about deprecating CompatHelper
  Project.toml
  docs/src/index.md
Labels: documentation

#299 Add a test to make sure the `version = "..."` line in the workflow file stays in sync with the version number in the `Project.toml` file
  Project.toml
  test/runtests.jl
  test/unit-tests.jl
Labels: test suite

#301 Add the `include_jll` keyword argument, which enables PRs to add/update `[compat]` entries for JLL dependencies
  Project.toml
  src/CompatHelper.jl
  src/api_rate_limiting.jl
  src/get_project_deps.jl
  src/main.jl
  src/new_versions.jl
  src/pull_requests.jl
  test/integration-test-utilities.jl
  test/integration-tests.jl
Labels: feature

#306 README: remove the Bors badge, and put all other badges into a single table
  README.md
Labels: documentation

#309 Merge `master` into `v3-dev`
  README.md
Labels: v3-dev

#308 Add CI checks to make sure that there are no merge conflicts between `v3-dev` and `master`
  .github/workflows/git_branch_checks.yml
  bors.toml
Labels: ci, v3-dev

#305 Implement fetching PullRequests
  Project.toml
  src/CompatHelper.jl
  src/pull_requests.jl
  test/patches.jl
  test/pull_requests.jl
  test/runtests.jl
Labels: feature, v3-dev

#322 README: fix some whitespace
  README.md
Labels: documentation
